timeout: 30000
enableInlineShortcodes: true

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true
